export const navigation = [
  { path: "/", title: "工作台", group: "总览", permission: "" },
  { path: "/account", title: "个人中心", group: "总览", permission: "" },
  {
    path: "/system/users",
    title: "用户管理",
    group: "系统",
    permission: "system:user:read",
  },
  {
    path: "/system/roles",
    title: "角色管理",
    group: "系统",
    permission: "system:role:read",
  },
  {
    path: "/system/permissions",
    title: "权限目录",
    group: "系统",
    permission: "system:permission:read",
  },
  {
    path: "/system/sessions",
    title: "用户会话",
    group: "系统",
    permission: "system:user:session:read",
  },
  {
    path: "/system/audits",
    title: "操作审计",
    group: "系统",
    permission: "system:operation-audit:read",
  },
  {
    path: "/notice",
    title: "公告管理",
    group: "内容",
    permission: "notice:read",
  },
  {
    path: "/notice/audits",
    title: "公告审计",
    group: "内容",
    permission: "notice:audit:read",
  },
  {
    path: "/product/categories",
    title: "商品类目",
    group: "商品",
    permission: "product:category:read",
  },
  {
    path: "/product/spu",
    title: "商品与规格",
    group: "商品",
    permission: "product:spu:read",
  },
  {
    path: "/member/points",
    title: "会员积分",
    group: "会员",
    permission: "member:points:read",
  },
  {
    path: "/inventory/stocks",
    title: "库存总览",
    group: "库存",
    permission: "inventory:stock:read",
  },
  {
    path: "/inventory/records",
    title: "库存流水",
    group: "库存",
    permission: "inventory:stock:read",
  },
  {
    path: "/inventory/reservations",
    title: "库存预占",
    group: "库存",
    permission: "inventory:reservation:read",
  },
  {
    path: "/payment/orders",
    title: "支付单",
    group: "支付",
    permission: "payment:order:read",
  },
  {
    path: "/payment/audits",
    title: "支付审计",
    group: "支付",
    permission: "payment:audit:read",
  },
  {
    path: "/payment/callback-events",
    title: "回调事件",
    group: "支付",
    permission: "payment:audit:read",
  },
  {
    path: "/payment/reconciliation",
    title: "数量核对",
    group: "支付",
    permission: "payment:audit:read",
  },
] as const;
